package main.java.mapper;

import main.java.model.Customer;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Tue Feb 04 12:01:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Tue Feb 04 12:01:26 CST 2020
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Tue Feb 04 12:01:26 CST 2020
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Tue Feb 04 12:01:26 CST 2020
     */
    Customer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Tue Feb 04 12:01:26 CST 2020
     */
    int updateByPrimaryKeySelective(Customer record, @Param("email") String email, @Param("id") String id, @Param("lastName") String lastName, @Param("gender") String gender);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_employee
     *
     * @mbg.generated Tue Feb 04 12:01:26 CST 2020
     */
    int updateByPrimaryKey(Customer record);
}